### ISSUE TITLE
预览不成功

### ISSUE THREAD

**Issue by gezhi0430** [getrebuild/rebuild-docs-preview#1]
提示：{"killed":false,"code":1,"signal":null,"cmd":"libreoffice --headless --convert-to pdf D:\\RBwenjian/20230425/file-1682381648295.download --outdir D:\\RBwenjian/20230425"}

http:\\XXXXX:3000能够成功，且外网可以访问，但配置RB文件预览服务后，预览不成功

**Comment by getrebuild** [comment]
对于 Windows 操作系统，LibreOffice 的命令为 `soffice.exe` 而非 `libreoffice`。按以下方式修改：

1. 修改 `.env` 文件
```
RBDP_LIBREOFFICE_BIN=soffice.exe
```
2. 将 soffice.exe 文件所在目录 [加入环境变量](https://blog.csdn.net/tjhyx2012/article/details/112793144)
